sudo apt-get --assume-yes install\
    curl\
    git\
    chromium-browser\
    gksu\
    leafpad\
    vlc\
    clementine\
    pinta\
    wine\
    playonlinux\
    sendmail\
    iptables-persistent\
    python3-pip\
    dropbox\
    python-gpgme\
    vim-nox\
    vim-gtk\
    vim-gnome\
    vim-athena\
    htop\
    steam
